StartupMaps/blog/config/routes.rb
Blog::Application.routes.draw do
 
  resources :groups do
    get "list_group_members"
  end  

  resources :startups

  resources :groups_startups

  
  resources :projects do

    get "change_launch_status", on: :member, as: :launch
    get "suggest"
    get "show_suggested"
    get "merge_request"
  end  

  root to: 'welcome#index'

end

StartupMaps/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :startup
  has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/entity.rb
class Entity < ActiveRecord::Base

	has_many :services 
	has_many :startups
	has_many :investors
	has_many :entity_statuses
	has_many :entity_work_portfolio 
	has_many :entity_video_links
	has_many :entity_social_links
	has_many :entity_needs
	has_many :entity_jobs
	has_many :entity_goals
	has_many :entity_available_internships
	has_many :senders, :through => :group_invitations
	has_many :receivers, :through => :group_invitations
	has_many :senders, :through => :send_merge_requests
	has_many :receivers, :through => :send_merge_requests
	has_many :subscriber, :through => :subscrtipion
	has_many :subscribee, :through => :subscrtipion

end

StartupMaps/blog/app/models/entity_goal.rb
class EntityGoal < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/entity_job.rb
class EntityJob < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/entity_need.rb
class EntityNeed < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/final.rb
class Final < ActiveRecord::Base
end

StartupMaps/blog/app/models/friendship.rb
class Friendship < ActiveRecord::Base
belongs_to :entity
belongs_to :friend, :class_name => "entity"


end

StartupMaps/blog/app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :startups
  has_many :posts
  has_many :comments, through: :posts
  has_many :likes, through: :posts
  has_many :resumes
  
  # Defintion: This method takes the group id, 
  # returns a list of group members. 
  # Input: group_id
  # Output: group_members
  # Author: Yomn El-Mistikawy

  def self.get_group_members(group)
    Startup.where(:id => (GroupsStartup.where(:group_id => group.id)))
  end
end

StartupMaps/blog/app/models/investor.rb
class Investor < ActiveRecord::Base
	belongs_to :Entity
end

StartupMaps/blog/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :liker, :class_name "startup"
  belongs_to :likable, :polymorphic => true
end

StartupMaps/blog/app/models/maha.rb
class Maha < ActiveRecord::Base
end

StartupMaps/blog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  belongs_to :startup
  has_many :comments
  has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/project.rb
class Project < ActiveRecord::Base

	 has_many :startups, :through => :startup_have_project
   

  # Definition: "A startup can see a list of his projects" 
  # This method allows you to get a list of projects and 
  # compares the project's id with the startup's id 
  # then start listing all the projects to a specific startup.
  # Input: entity_id, startup_id, project_id.
  # Output: project_id "all project description in a list".
  # Author: Hana Magdy.

  def  self.listing_projects(startup)
    @startups_listing_projects = StartupHaveProject.select(:project_id).where(:startup_id => startup.id)
    Project.where(:id => @startups_listing_projects)

	end


  # Defintion: This method takes a project as input
  # and searches the projects table for projects of
  # same geographical location and category and sends
  # the results to the suggest function in the project
  # controller.
  # Input: project
  # Output: a list of suggested projects
  # Author: Yomn El-Mistikawy

  def  self.get_suggest(project, startup)
    @projects_owned_by_startup_ids = StartupHaveProject.select(:project_id).where(:startup_id => startup.id)
    @suggested_projects = Project.where(:location => project.location, :category => project.category).where.not(:id => project.id, :id => @projects_owned_by_startup_ids)
  end	

end

StartupMaps/blog/app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :group
	belongs_to :startup
	has_many :comments
	has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :Entity
end

StartupMaps/blog/app/models/startup.rb
class Startup < ActiveRecord::Base
	belongs_to :Entity
	has_many :startup_resources
	has_and_belongs_to_many :groups
	has_many :posts, through: :groups
	has_many :comments, through: :groups
	has_many :likes, through: :groups
	has_many :resumes, through: :groups
	has_many :projects, :through => :startup_have_project
	has_many :resumes, through: :groups
end

StartupMaps/blog/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :entities
	
end

StartupMaps/blog/app/models/try.rb
class Try < ActiveRecord::Base
end

StartupMaps/blog/app/models/user.rb
class User < ActiveRecord::Base
	has_many :subscriptions 
end

StartupMaps/blog/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # == Begin  == 
  # Definition: "A startup can see a list of his projects" 
  # This method allows you to get a list of projects and 
  # moves with a session_id of an entity in order to 
  # list all the project's of the startup
  # that belong to a specific startup and is linked to the index HTML file
  # respond_to --> gives a direct access to the HTML/XML/PDF whatever is it
  # it's reachable and knows what's happening in the file.
  # Input: entity_id, startup_id.
  # Output: project_id "all project description in a list".
  # Author: Hana Magdy.

  def index
    session[:entity_id] = 1
    @projects = Project.listing_projects(Startup.find(session[:entity_id]))
    # @projects = Project.all
    # @startup = Startup.find(session[:entity_id])
    # @projects = @startup.project.find( :all)

    respond_to do |format|
      format.html
    end
  end


  # Defintion: This method takes the project_id and session id
  # as input and calls get_suggested() to show a list of 
  # projects with the same geographical location and
  # category to the startup's opened project.The suggestions 
  # are only shown for project owners. Moreover, if there are no 
  # suggestions, a message is shown stating so.
  # Input: project_id, entity_id
  # Output: project_id, suggested_project
  # Author: Yomn El-Mistikawy

  def suggest
    if (StartupHaveProject.check_ownership(Project.find(params[:project_id]), Startup.find(session[:entity_id])).size != 0)
      @suggested = Project.get_suggest(Project.find(params[:project_id]), Startup.find(session[:entity_id]))
    else
      render text: ""
    end
  end


  # Defintion: This method takes the suggested project id
  # as input and views the project with a button for the startup
  # to send a merge request to the project owner.
  # Input: suggested_project
  # Output: project_id, suggested_project
  # Author: Yomn El-Mistikawy

  def show_suggested
    @project = Project.find(params[:suggested_project])
  end


  # Definition: "As a startup, I can set a project goal, milestone,
  # requirements (roles, resources) "
  # This method shows all details of a project
  # that belong to a specific startup and is linked to the show HTML file
  # which also includes the launch and editing part
  # respond_to --> gives a direct access to the HTML/XML/PDF whatever is it
  # it's reachable and knows what's happening in the file.
  # Input: Project_id.
  # Output: Project_id "all project description".
  # Author: Hana Magdy.

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html
    end
  end


   def new
    @project = Project.new
  end


  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to @project
  end


  private
  def project_params
    params[:project].permit(:name, :category, :location, :description)
  end
  
end

StartupMaps/blog/app/helpers/maha_helper.rb
module MahaHelper
end

StartupMaps/blog/app/helpers/projects_helper.rb
module ProjectsHelper
end

StartupMaps/blog/app/helpers/try_helper.rb
module TryHelper
end

StartupMaps/blog/app/views/projects/index.html.erb
  <!-- == Begin  == 
  # Definition: "A startup can see a list of his projects" 
  # This method allows you to get a list of projects. 
  # that belong to a specific startup with all its categories
  # link_to, it gives it the privileges to link it to the project.
  # Input: entity_id, startup_id.
  # Output: project_id "all project description in a list".
  # Author: Hana Magdy. -->
  
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Milestones</th>
      <th>Location</th>
      <th>Goals</th>
      <th>Requirements</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>

      <tr>
        <td> <%= link_to project.id, project %> </td>
        <td> <%= link_to project.name, project %> </td>
        <td> <%= project.description %> </td>
        <td> <%= project.milestones %> </td>
        <td> <%= project.location %> </td>
        <td> <%= project.goals %> </td>
        <td> <%= project.requirements %> </td>
      </tr>
    
    <% end %>
  </tbody>
</table>


  <!-- == End  ==   -->

StartupMaps/blog/app/views/projects/new.html.erb
  <!-- Just added the colors :)
  Author: Hana Magdy  -->

<style type="text/css">

  h1 {
    color: #FF3399;
  }

  p {
    color: #0099FF;
  }
  </style>

<h1> Create New Project </h1>


<%= form_for @project do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit("Create project") %>
  </p>
<% end %>

StartupMaps/blog/app/views/projects/show.html.erb
  <!-- Just added the colors :)
  Author: Hana Magdy  -->

<style type="text/css">

  h1 {
    color: #FF3399;
  }

  p {
    color: #0099FF;
  }

</style>

<h1> Your project details </h1>
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
 
<p>
  <strong>Category:</strong>
  <%= @project.category %>
</p>

<p>
  <strong>Location:</strong>
  <%= @project.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @project.goals %>
</p>

<p>
  <strong>Milestones:</strong>
  <%= @project.milestones %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @project.requirements %>
</p>

StartupMaps/blog/app/views/projects/show_suggested.html.erb
<!-- # Defintion: This shows a project profile with
     # a send merge request button
     # Input: project_id, suggested_project
     # Output: project_id, suggested_project
     # Author: Yomn El-Mistikawy -->

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @project.location %>
</p>

<p>
  <strong>Category:</strong>
  <%= @project.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @project.requirements %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @project.goals %>
</p>

<p>
  <strong>Milestones:</strong>
  <%= @project.milestones %>
</p>

StartupMaps/blog/app/views/projects/suggest.html.erb
<!-- # Defintion: This shows a a list of suggested
     # projects and it enables the user to show 
     # the profile of a suggested project.
     # Input: project_id, @suggested
     # Output: project_id, suggested_project
     # Author: Yomn El-Mistikawy -->

<% if @suggested.size <= 0 %>
  <div>
    <p> There are no suggestions </p>
  </div>
<% else %>
  <h1>Listing suggested projects</h1>
  <table>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Location</th>
    </tr>
    <% @suggested.each do |p| %>
      <tr>
        <td><%= p.name %></td>
        <td><%= p.category%></td>
        <td><%= p.location%></td>
        <td><%= link_to 'Show',project_show_suggested_path(suggested_project: p)%></td>
      </tr>
    <% end %>
  </table>
<% end %>