StartupMaps/blog/config/routes.rb
Blog::Application.routes.draw do
 
  resources :groups do
    get "list_group_members"
  end  

  resources :startups

  resources :groups_startups

  
  resources :projects do

    get "change_launch_status", on: :member, as: :launch
    get "suggest"
    get "show_suggested"
    get "merge_request"
  end  

  root to: 'welcome#index'

end

StartupMaps/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :startup
  has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/entity.rb
class Entity < ActiveRecord::Base

	has_many :services 
	has_many :startups
	has_many :investors
	has_many :entity_statuses
	has_many :entity_work_portfolio 
	has_many :entity_video_links
	has_many :entity_social_links
	has_many :entity_needs
	has_many :entity_jobs
	has_many :entity_goals
	has_many :entity_available_internships
	has_many :senders, :through => :group_invitations
	has_many :receivers, :through => :group_invitations
	has_many :senders, :through => :send_merge_requests
	has_many :receivers, :through => :send_merge_requests
	has_many :subscriber, :through => :subscrtipion
	has_many :subscribee, :through => :subscrtipion

end

StartupMaps/blog/app/models/entity_goal.rb
class EntityGoal < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/entity_job.rb
class EntityJob < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/entity_need.rb
class EntityNeed < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/final.rb
class Final < ActiveRecord::Base
end

StartupMaps/blog/app/models/friendship.rb
class Friendship < ActiveRecord::Base
belongs_to :entity
belongs_to :friend, :class_name => "entity"


end

StartupMaps/blog/app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :startups
  has_many :posts
  has_many :comments, through: :posts
  has_many :likes, through: :posts
  has_many :resumes
  
  # Defintion: This method takes the group id, 
  # returns a list of group members. 
  # Input: group_id
  # Output: group_members
  # Author: Yomn El-Mistikawy

  def self.get_group_members(group)
    Startup.where(:id => (GroupsStartup.where(:group_id => group.id)))
  end
end

StartupMaps/blog/app/models/investor.rb
class Investor < ActiveRecord::Base
	belongs_to :Entity
end

StartupMaps/blog/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :liker, :class_name "startup"
  belongs_to :likable, :polymorphic => true
end

StartupMaps/blog/app/models/maha.rb
class Maha < ActiveRecord::Base
end

StartupMaps/blog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  belongs_to :startup
  has_many :comments
  has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/project.rb
class Project < ActiveRecord::Base

	 has_many :startups, :through => :startup_have_project
   

  # Definition: "A startup can see a list of his projects" 
  # This method allows you to get a list of projects and 
  # compares the project's id with the startup's id 
  # then start listing all the projects to a specific startup.
  # Input: entity_id, startup_id, project_id.
  # Output: project_id "all project description in a list".
  # Author: Hana Magdy.

  def  self.listing_projects(startup)
    @startups_listing_projects = StartupHaveProject.select(:project_id).where(:startup_id => startup.id)
    Project.where(:id => @startups_listing_projects)

	end


  # Defintion: This method takes a project as input
  # and searches the projects table for projects of
  # same geographical location and category and sends
  # the results to the suggest function in the project
  # controller.
  # Input: project
  # Output: a list of suggested projects
  # Author: Yomn El-Mistikawy

  def  self.get_suggest(project, startup)
    @projects_owned_by_startup_ids = StartupHaveProject.select(:project_id).where(:startup_id => startup.id)
    @suggested_projects = Project.where(:location => project.location, :category => project.category).where.not(:id => project.id, :id => @projects_owned_by_startup_ids)
  end	

end

StartupMaps/blog/app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :group
	belongs_to :startup
	has_many :comments
	has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :Entity
end

StartupMaps/blog/app/models/startup.rb
class Startup < ActiveRecord::Base
	belongs_to :Entity
	has_many :startup_resources
	has_and_belongs_to_many :groups
	has_many :posts, through: :groups
	has_many :comments, through: :groups
	has_many :likes, through: :groups
	has_many :resumes, through: :groups
	has_many :projects, :through => :startup_have_project
	has_many :resumes, through: :groups
end

StartupMaps/blog/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :entities
	
end

StartupMaps/blog/app/models/try.rb
class Try < ActiveRecord::Base
end

StartupMaps/blog/app/models/user.rb
class User < ActiveRecord::Base
	has_many :subscriptions 
end

StartupMaps/blog/app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :set_startup, only: [:show, :edit, :update, :destroy]

# Please note that any code code that is 
# not written above it a comment and "Author: Maha Salah Eldin" is not part of my user story 
# and is just added for testing purposes in order to get my code reviewed by scenario reviwers.
# This is due to the delay in merging the user stories my user story is depenedent on.

  def index
    @startups = Startup.all
  end

  def show
  end

  def new
    @startup = Startup.new
  end

  def edit
  end

  def create
    @startup = Startup.new(startup_params)
    # The following line calls mthod create_geo_group from the application helper 
    #in order to create a geographic group for the inserted location, if it doesn't already exist.
    # Author: Maha Salah Eldin.
    @newgeo_id = create_geo_group(startup_params[:location])

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: 'Startup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @startup }
      else
        format.html { render action: 'new' }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
    # The following line calls method create_groups_startups from the application controller
    # in order to add the startup to the corresponding geographic group.
    # Author: Maha Salah Eldin.
    create_groups_startups(startup_params[:name], @newgeo_id)
  end

  
  def update
    respond_to do |format|
    # The following if block checks if the user updated his location, if yes then create_geo_groups method and 
    # create_groups_startups are called,  thus, creating a group for the new location if it doesn't exist, 
    # and adding the startup to it.
    # Author: Maha Salah Eldin.
      if @startup.update_attribute(:location, @startup.location)
        @newgeo_id = create_geo_group(startup_params[:location])
        create_groups_startups(startup_params[:name], @newgeo_id)
      end

      if @startup.update(startup_params)
        format.html { redirect_to @startup, notice: 'Startup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # The following 2 lines line save the location and the id of the startup before it is destroyed.
    # Author: Maha Salah Eldin.
    @location = @startup.location
    @id = @startup.id
    @startup.destroy 
    # The following 2 lines call methods destroy_groups_startups and destroy_geo_group 
    # from the apllication helper in order to destroy remove the destryed startup from all groups,
    # and destroy the geograohic group the destryed startup belongs to 
    # in case it was the only startup in this group.
    # Author : Maha Salah Eldin.
    destroy_groups_startups(@id)
    destroy_geo_group(@location)

    respond_to do |format|
      format.html { redirect_to startups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_startup
      @startup = Startup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def startup_params
      params.require(:startup).permit(:name, :location)
    end
end

StartupMaps/blog/app/helpers/maha_helper.rb
module MahaHelper
end

StartupMaps/blog/app/helpers/startups_helper.rb
module StartupsHelper
end

StartupMaps/blog/app/helpers/try_helper.rb
module TryHelper
end

StartupMaps/blog/app/views/startups/edit.html.erb
<h1>Editing startup</h1>

<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @startup %> |
<%= link_to 'Back', startups_path %>

StartupMaps/blog/app/views/startups/index.html.erb
<h1>Listing startups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @startups.each do |startup| %>
      <tr>
        <td><%= startup.name %></td>
        <td><%= startup.location %></td>
        <td><%= link_to 'Show', startup %></td>
        <td><%= link_to 'Edit', edit_startup_path(startup) %></td>
        <td><%= link_to 'Destroy', startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Startup', new_startup_path %>

StartupMaps/blog/app/views/startups/new.html.erb
<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

StartupMaps/blog/app/views/startups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @startup.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @startup.location %>
</p>

<%= link_to 'Edit', edit_startup_path(@startup) %> |
<%= link_to 'Back', startups_path %>