StartupMaps/blog/config/routes.rb
Blog::Application.routes.draw do
 
  resources :groups do
    get "list_group_members"
  end  

  resources :startups

  resources :groups_startups

  
  resources :projects do

    get "change_launch_status", on: :member, as: :launch
    get "suggest"
    get "show_suggested"
    get "merge_request"
  end  

  root to: 'welcome#index'

end

StartupMaps/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :startup
  has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/entity.rb
class Entity < ActiveRecord::Base

	has_many :services 
	has_many :startups
	has_many :investors
	has_many :entity_statuses
	has_many :entity_work_portfolio 
	has_many :entity_video_links
	has_many :entity_social_links
	has_many :entity_needs
	has_many :entity_jobs
	has_many :entity_goals
	has_many :entity_available_internships
	has_many :senders, :through => :group_invitations
	has_many :receivers, :through => :group_invitations
	has_many :senders, :through => :send_merge_requests
	has_many :receivers, :through => :send_merge_requests
	has_many :subscriber, :through => :subscrtipion
	has_many :subscribee, :through => :subscrtipion

end

StartupMaps/blog/app/models/entity_goal.rb
class EntityGoal < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/entity_job.rb
class EntityJob < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/entity_need.rb
class EntityNeed < ActiveRecord::Base
	belongs_to :entity
end

StartupMaps/blog/app/models/final.rb
class Final < ActiveRecord::Base
end

StartupMaps/blog/app/models/friendship.rb
class Friendship < ActiveRecord::Base
belongs_to :entity
belongs_to :friend, :class_name => "entity"


end

StartupMaps/blog/app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :startups
  has_many :posts
  has_many :comments, through: :posts
  has_many :likes, through: :posts
  has_many :resumes
  
  # Defintion: This method takes the group id, 
  # returns a list of group members. 
  # Input: group_id
  # Output: group_members
  # Author: Yomn El-Mistikawy

  def self.get_group_members(group)
    Startup.where(:id => (GroupsStartup.where(:group_id => group.id)))
  end
end

StartupMaps/blog/app/models/investor.rb
class Investor < ActiveRecord::Base
	belongs_to :Entity
end

StartupMaps/blog/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :liker, :class_name "startup"
  belongs_to :likable, :polymorphic => true
end

StartupMaps/blog/app/models/maha.rb
class Maha < ActiveRecord::Base
end

StartupMaps/blog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  belongs_to :startup
  has_many :comments
  has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/project.rb
class Project < ActiveRecord::Base

	 has_many :startups, :through => :startup_have_project
   

  # Definition: "A startup can see a list of his projects" 
  # This method allows you to get a list of projects and 
  # compares the project's id with the startup's id 
  # then start listing all the projects to a specific startup.
  # Input: entity_id, startup_id, project_id.
  # Output: project_id "all project description in a list".
  # Author: Hana Magdy.

  def  self.listing_projects(startup)
    @startups_listing_projects = StartupHaveProject.select(:project_id).where(:startup_id => startup.id)
    Project.where(:id => @startups_listing_projects)

	end


  # Defintion: This method takes a project as input
  # and searches the projects table for projects of
  # same geographical location and category and sends
  # the results to the suggest function in the project
  # controller.
  # Input: project
  # Output: a list of suggested projects
  # Author: Yomn El-Mistikawy

  def  self.get_suggest(project, startup)
    @projects_owned_by_startup_ids = StartupHaveProject.select(:project_id).where(:startup_id => startup.id)
    @suggested_projects = Project.where(:location => project.location, :category => project.category).where.not(:id => project.id, :id => @projects_owned_by_startup_ids)
  end	

end

StartupMaps/blog/app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :group
	belongs_to :startup
	has_many :comments
	has_many :likes, :as => :likable
end

StartupMaps/blog/app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :Entity
end

StartupMaps/blog/app/models/startup.rb
class Startup < ActiveRecord::Base
	belongs_to :Entity
	has_many :startup_resources
	has_and_belongs_to_many :groups
	has_many :posts, through: :groups
	has_many :comments, through: :groups
	has_many :likes, through: :groups
	has_many :resumes, through: :groups
	has_many :projects, :through => :startup_have_project
	has_many :resumes, through: :groups
end

StartupMaps/blog/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :entities
	
end

StartupMaps/blog/app/models/try.rb
class Try < ActiveRecord::Base
end

StartupMaps/blog/app/models/user.rb
class User < ActiveRecord::Base
	has_many :subscriptions 
end

StartupMaps/blog/app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController
  before_action :set_group_member, only: [:show, :edit, :update, :destroy]

  # GET /group_members
  # GET /group_members.json
  def index
    @group_members = GroupMember.all
  end

  # GET /group_members/1
  # GET /group_members/1.json
  def show
  end

  # GET /group_members/new
  def new
    @group_member = GroupMember.new
  end

  # GET /group_members/1/edit
  def edit
  end

  # POST /group_members
  # POST /group_members.json
  def create
    @group_member = GroupMember.new(group_member_params)

    respond_to do |format|
      if @group_member.save
        format.html { redirect_to @group_member, notice: 'Group member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group_member }
      else
        format.html { render action: 'new' }
        format.json { render json: @group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_members/1
  # PATCH/PUT /group_members/1.json
  def update
    respond_to do |format|
      if @group_member.update(group_member_params)
        format.html { redirect_to @group_member, notice: 'Group member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_members/1
  # DELETE /group_members/1.json
  def destroy
    @group_member.destroy
    respond_to do |format|
      format.html { redirect_to group_members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_member
      @group_member = GroupMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_member_params
      params.require(:group_member).permit(:enitity_id, :datejoined, :groupcreator)
    end
end

StartupMaps/blog/app/helpers/group_members_helper.rb
module GroupMembersHelper
end

StartupMaps/blog/app/helpers/try_helper.rb
module TryHelper
end

StartupMaps/blog/app/views/group_members/_form.html.erb
<%= form_for(@group_member) do |f| %>
  <% if @group_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_member.errors.count, "error") %> prohibited this group_member from being saved:</h2>

      <ul>
      <% @group_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :group_name %><br>
    <%= f.text_field :group_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

StartupMaps/blog/app/views/group_members/edit.html.erb
<h1>Editing group_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_member %> |
<%= link_to 'Back', group_members_path %>

StartupMaps/blog/app/views/group_members/index.html.erb
<h1>Listing group_members</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Group name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @group_members.each do |group_member| %>
      <tr>
        <td><%= group_member.user_name %></td>
        <td><%= group_member.group_name %></td>
        <td><%= link_to 'Show Group', group_member %></td>
       
        <td><%= link_to 'leave group', group_member, method: :delete, data: { confirm: 'Are you sure you would like to leave group?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group member', new_group_member_path %>

StartupMaps/blog/app/views/group_members/new.html.erb
<h1>New group_member</h1>

<%= render 'form' %>

<%= link_to 'Back', group_members_path %>

StartupMaps/blog/app/views/group_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @group_member.user_name %>
</p>

<p>
  <strong>Group name:</strong>
  <%= @group_member.group_name %>
</p>

<%= link_to 'Back', group_members_path %>